version: "3"

services:
  # 이곳에 컨테이너를 하나씩 입력합니다. (예시에서는 demo_postgres14라는 컨테이너 하나)
  demo_postgres14:
    # 도커 허브에서 PostgreSQL 14버전 공식 이미지를 사용합니다.
    image: postgres:14
    environment:
      # 이미지가 인식하는 환경 변수 중 일부를 이곳에 씁니다.
      TZ: Asia/Seoul
      POSTGRES_DB: demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      # "접속할_포트:컨테이너_내부_포트"
      #  접속할 포트는 우리가 수정할 수 있습니다.
      #  컨테이너 내부 포트는 수정할 수 없습니다.
      - 5433:5432
    restart: on-failure
    volumes:
      # "링크할_우리_폴더:컨테이너_내부_폴더"
      #  링크할 우리 폴더는 '볼륨 컨테이너'라는 것으로 대신할 수 있습니다.
      - sticky_volume_demo_postgres14:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro

# 볼륨 컨테이너는 지금 중요한 개념은 아닙니다.
volumes:
  sticky_volume_demo_postgres14: